### ISSUE TITLE
Unable to reproduce as Dataset is not linked

### ISSUE THREAD

**Issue by iveksl2** [domrussel/wsj_comment_analysis#1]
Thank you for providing the accompanying code in the op-ed! I was tring to reproduce the findings but the dataset here: https://dominic-russel.netlify.app/files/wsj_comment_analysis.html is not provided

**Comment by domrussel** [comment]
Hi -- thanks for you interest! You can now find the dataset cleaned_wsj_comments_1214_noon.csv here: https://github.com/domrussel/wsj_comment_analysis/blob/main/cleaned_wsj_comments_1214_noon.csv.

Best of luck with your work

**Comment by iveksl2** [comment]
Worked thanks. I rarely see the reproducible code accompanied with an article and even more rarely is it actually reproducible. I think its a nice learning & teaching example of applied NLP work. Thanks
